## Numpy array operations

In [1]:
import numpy as np

In [5]:
arr = np.arange(1, 12)
print("Basic slicing: ", arr[2:7])
print("With step: ", arr[1:8:2]) # in every two step
print("Negative indexing: ", arr[-3])

Basic slicing:  [3 4 5 6 7]
With step:  [2 4 6 8]
Negative indexing:  9


In [ ]:
arr_2d = np.array([[1, 2, 3], # 0th row
                   [4, 5, 6], # 1st row
                   [7, 8, 8]]) # 2nd row
print("Specific element: ", arr_2d[1, 2]) # get 2nd element from 1st row
print("Entire row: ", arr_2d[1]) # get 1st row
print("Specific column: ", arr_2d[:, 1]) # getting 1st column

Specific element:  6
Entire row:  [4 5 6]
Entire  [2 5 8]


## Sorting

In [12]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted array: ", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=0))

Sorted array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]


## Filter

In [26]:

numbers_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers_array[numbers_array % 2 == 0]
print("Even numbers: ", even_number)

Even numbers:  [ 2  4  6  8 10]


## Filter with mask

In [27]:

mask = numbers_array > 5
print("Numbers greater tha 5: ", numbers_array[mask])

Numbers greater tha 5:  [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [29]:
indices = [0, 2, 4]
print(numbers_array[indices]) #[1 3 5]

where_result = np.where(numbers_array > 5)
print("NP where", numbers_array[where_result])


[1 3 5]
NP where [ 6  7  8  9 10]


In [36]:
condition_array = np.where(numbers_array > 5, numbers_array*2, numbers_array) # if numbers_array > 5 then number_array*2 else numbers_array
print(condition_array)


[ 1  2  3  4  5 12 14 16 18 20]


## Adding and removing data

In [41]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
combined= np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])
print("Compatibility shapes: ", a.shape == b.shape)

Compatibility shapes:  False


In [49]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row)) # vstack() always add a new row in the matrices
print("original array: ", original)
print("with new row added: ", with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col)) # hstack() always add a new column in the matrices
print("With new column: ", with_new_col)

original array:  [[1 2]
 [3 4]]
with new row added:  [[1 2]
 [3 4]
 [5 6]]
With new column:  [[1 2 7]
 [3 4 8]]


In [50]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2) # np.delete(source, index)
print("Array after deleted: ", deleted)

Array after deleted:  [1 2 4 5]
