# Analysing 50 students

In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [34]:
std_data = np.genfromtxt("student_performance_50.csv", delimiter = ",", skip_header=0, names=True, dtype=None, encoding="utf-8")
print(std_data)


[( 1, 'Aarav', 83, 96, 73, 59) ( 2, 'Sita', 87, 52, 65, 83)
 ( 3, 'Rohan', 63, 67, 55, 55) ( 4, 'Anisha', 68, 97, 80, 84)
 ( 5, 'Bibek', 68, 47, 66, 97) ( 6, 'Pratik', 46, 68, 88, 74)
 ( 7, 'Samir', 82, 46, 65, 77) ( 8, 'Nisha', 56, 66, 88, 69)
 ( 9, 'Sujan', 93, 71, 86, 72) (10, 'Aayush', 60, 59, 91, 95)
 (11, 'Puja', 88, 99, 96, 47) (12, 'Roshan', 81, 95, 51, 65)
 (13, 'Sneha', 53, 83, 62, 48) (14, 'Kiran', 69, 58, 94, 53)
 (15, 'Suman', 70, 97, 46, 64) (16, 'Riya', 72, 91, 51, 88)
 (17, 'Nabin', 52, 91, 79, 58) (18, 'Asmita', 61, 80, 94, 84)
 (19, 'Bikash', 48, 46, 50, 98) (20, 'Sarita', 86, 48, 98, 73)
 (21, 'Raj', 62, 70, 88, 78) (22, 'Manisha', 54, 80, 58, 75)
 (23, 'Dipesh', 92, 59, 52, 58) (24, 'Sabina', 67, 84, 65, 60)
 (25, 'Ashish', 89, 62, 91, 97) (26, 'Kabita', 68, 70, 69, 89)
 (27, 'Sandip', 85, 73, 59, 89) (28, 'Prabin', 45, 69, 51, 53)
 (29, 'Alisha', 68, 45, 88, 52) (30, 'Niraj', 68, 55, 95, 61)
 (31, 'Shreya', 52, 79, 79, 77) (32, 'Milan', 49, 86, 83, 85)
 (33, 'Sanja

## Extract only student id, math, science, english, computer

In [35]:
numeric_data = np.column_stack((std_data["student_id"], std_data["math"], std_data["science"], std_data["english"], std_data["computer"]))
print(numeric_data)

[[ 1 83 96 73 59]
 [ 2 87 52 65 83]
 [ 3 63 67 55 55]
 [ 4 68 97 80 84]
 [ 5 68 47 66 97]
 [ 6 46 68 88 74]
 [ 7 82 46 65 77]
 [ 8 56 66 88 69]
 [ 9 93 71 86 72]
 [10 60 59 91 95]
 [11 88 99 96 47]
 [12 81 95 51 65]
 [13 53 83 62 48]
 [14 69 58 94 53]
 [15 70 97 46 64]
 [16 72 91 51 88]
 [17 52 91 79 58]
 [18 61 80 94 84]
 [19 48 46 50 98]
 [20 86 48 98 73]
 [21 62 70 88 78]
 [22 54 80 58 75]
 [23 92 59 52 58]
 [24 67 84 65 60]
 [25 89 62 91 97]
 [26 68 70 69 89]
 [27 85 73 59 89]
 [28 45 69 51 53]
 [29 68 45 88 52]
 [30 68 55 95 61]
 [31 52 79 79 77]
 [32 49 86 83 85]
 [33 72 51 53 52]
 [34 56 78 77 92]
 [35 99 67 68 81]
 [36 79 88 84 66]
 [37 71 79 45 79]
 [38 81 91 58 47]
 [39 45 49 70 99]
 [40 58 83 71 53]
 [41 59 59 70 86]
 [42 57 95 76 83]
 [43 93 96 76 48]
 [44 74 81 67 83]
 [45 89 59 87 73]
 [46 80 57 76 51]
 [47 95 66 72 46]
 [48 86 89 97 50]
 [49 72 72 88 88]
 [50 64 74 55 99]]


## Performing calculation

In [ ]:
print("Mean: ", np.mean(numeric_data[:, 1:], axis=0))
print("Median: ", np.median(numeric_data[:, 1:], axis=0))
print("Average: ", np.average(numeric_data[:, 1:], axis=0))
print("Average: ", np.average(numeric_data[:, 1:], axis=0))

Mean:  [70.3  72.46 72.92 71.86]
Median:  [68.5 71.5 72.5 73.5]
Average:  [70.3  72.46 72.92 71.86]


### Filtering the data

In [55]:
filtered_data = np.where(numeric_data>80, numeric_data, 0)
print("Filtered data: ", filtered_data)

Filtered data:  [[ 0 83 96  0  0]
 [ 0 87  0  0 83]
 [ 0  0  0  0  0]
 [ 0  0 97  0 84]
 [ 0  0  0  0 97]
 [ 0  0  0 88  0]
 [ 0 82  0  0  0]
 [ 0  0  0 88  0]
 [ 0 93  0 86  0]
 [ 0  0  0 91 95]
 [ 0 88 99 96  0]
 [ 0 81 95  0  0]
 [ 0  0 83  0  0]
 [ 0  0  0 94  0]
 [ 0  0 97  0  0]
 [ 0  0 91  0 88]
 [ 0  0 91  0  0]
 [ 0  0  0 94 84]
 [ 0  0  0  0 98]
 [ 0 86  0 98  0]
 [ 0  0  0 88  0]
 [ 0  0  0  0  0]
 [ 0 92  0  0  0]
 [ 0  0 84  0  0]
 [ 0 89  0 91 97]
 [ 0  0  0  0 89]
 [ 0 85  0  0 89]
 [ 0  0  0  0  0]
 [ 0  0  0 88  0]
 [ 0  0  0 95  0]
 [ 0  0  0  0  0]
 [ 0  0 86 83 85]
 [ 0  0  0  0  0]
 [ 0  0  0  0 92]
 [ 0 99  0  0 81]
 [ 0  0 88 84  0]
 [ 0  0  0  0  0]
 [ 0 81 91  0  0]
 [ 0  0  0  0 99]
 [ 0  0 83  0  0]
 [ 0  0  0  0 86]
 [ 0  0 95  0 83]
 [ 0 93 96  0  0]
 [ 0  0 81  0 83]
 [ 0 89  0 87  0]
 [ 0  0  0  0  0]
 [ 0 95  0  0  0]
 [ 0 86 89 97  0]
 [ 0  0  0 88 88]
 [ 0  0  0  0 99]]
